### ISSUE TITLE
JSONAPI relationship missing in the swagger documentation

### ISSUE THREAD

**Issue by kurianbenoy-aot** [thomaxxl/safrs#87] opened 2021-01-05 11:58 UTC
According to JSONAPI specs, the documentation should also include relationship like:

```
http://example.com/articles/1/relationships/author
http://example.com/author/1/relationships/articles
```

https://jsonapi.org/format/#document-resource-object-relationships

Will it be possible to include such a relationship also in the swagger documentation being generated?

**Comment by thomaxxl** [comment] 2021-01-05 12:30
The relationship url format is configurable: (`RELATIONSHIP_URL_FMT = "{}{}"` in config.py).
However, there seems to be a regression here: it used to be possible to specify the settings as arguments to flask `app.config`

I just commited a fix for this, you should be able to use this version with 

```python
app.config.update(RELATIONSHIP_URL_FMT="{}relationships/{}")
```

The relationships willthen  be exposed at /relationships/ .

The link you refer to applies to json responses, not to URLs?

**Comment by kurianbenoy-aot** [comment] 2021-01-08 04:05
In frameworks like flask-rest-jsonapi which are fully compliant with JSONAPI they have 
these relationship URL along with the foreign key type relationship which is by default shown in safrs library.

Reference -> https://flask-rest-jsonapi.readthedocs.io/en/latest/quickstart.html

The change you made just makes:

http://example.com/articles/1/author -> http://example.com/articles/1/relationship/author

http://example.com/author/1/articles -> http://example.com/author/1/relationships/articles

While really in the API documentation, we want:

```
http://example.com/articles/1/author
http://example.com/author/1/articles

(GET, POST, PATCH, DELETE)
http://example.com/articles/1/relationships/author
http://example.com/author/1/relationships/articles
```

Also as a side note, I would like to thanks for helping in your previous solution suggestion with custom_swagger and it worked for my use case. 

I would like to contribute an example to swags examples with `flask-rest-jsonapi` library get started using SAFRS library. Will you be interested to accept it, if I put a PR?

**Comment by thomaxxl** [comment] 2021-01-08 08:23
It seems I didn't follow the best practices described here : https://jsonapi.org/recommendations/#urls-relationships .
But, I don't really understand the benefit of adding an additional url, could you explain this some more?

I also don't understand what PR you want to add? I can accept PRs if nothing breaks.

**Comment by kurianbenoy-aot** [comment] 2021-01-18 03:56
Thanks for accepting the PR. I don't really know the benefit of having that additional relationship URL. In the case of flask-rest-jsonapi which are trying to be REST compatible, in order to create a new relationship for a particular resource, such an endpoint is necessary as shown in docs:

https://flask-rest-jsonapi.readthedocs.io/en/latest/quickstart.html#create-relationship

**Closed** 2021-01-18 16:49 UTC
